### ISSUE TITLE
Is cordova on Ubuntu supported?

### ISSUE THREAD

**Issue by jonofe** [ConnectSDK/Connect-SDK-Cordova-Plugin#13]
Hi Guys,

I'm trying to create a very simple TV control application which I can use on my Linux (Ubuntu) server to integrate my LG TV's in my home automation.

Is that possible by using Connect-SDK with the cordova-plugin on Ubuntu?

I already setup the LG SDK emulator and installed cordova on my ubuntu server and I installed the Hello_Connect example. but I ran into an js-error.

Therefore my first question whether this setup should work at all?

Thanks for a short feedback.

BR
André

**Comment by khk624** [comment]
Sorry for late feedback.
Currently, we're not supporting cordova-ubuntu; Instead, if you want to make home automation for LG WebOSTV, you can do it through websocket. (Please check WebOSTVService code either iOS or Android), but that's only for webOSTV.

and about the second questions, you'd better go to http://developer.lge.com.
They have better feedback for webOSTV SDK.
