### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by drastick** [ConnectSDK/Connect-SDK-Cordova-Plugin#14]
On the website there are no new downloads since v1.3.1. Seems like other things are getting love but not Cordova.

**Comment by viveksekar** [comment]
@drastick apologies from our side, for not keeping the cordova plugin up-to-date. we are under staffed in this area now, trying our best to fill that gap.

**Comment by drastick** [comment]
Any ideas on a timeframe that we might see some progress?

**Comment by drastick** [comment]
I'm guessing it is now safe to say that this project is dead?

**Comment by viveksekar** [comment]
@drastick we are starting the work on this project again. As of end of last week, we have 1 engineer working on getting the cordova plugin up to date with the iOS and Android repos.

**Comment by drastick** [comment]
So, it's a month later and still not even one new commit.  Are you sure this isn't dead?
