### ISSUE TITLE
Problem to use with AdMobPro

### ISSUE THREAD

**Issue by Valkno** [ConnectSDK/Connect-SDK-Cordova-Plugin#50]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> Error: more than one library with package name 'com.google.android.gms'
```

I have those plugins, but i detect the problem is with AdMobPro plugin
The problem is because Admobpro use the latest libraries 8..., and ConnectSDK use 7...

```
com.dawsonloudon.videoplayer 1.0.0 "VideoPlayer"
cordova-plugin-admobpro 2.16.0 "AdMob Plugin Pro"
cordova-plugin-connectsdk 1.6.0 "Connect SDK"
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-extension 1.5.1 "Cordova Plugin Extension"
cordova-plugin-inappbrowser 1.3.0 "InAppBrowser"
cordova-plugin-splashscreen 3.2.1 "Splashscreen"
cordova-plugin-statusbar 2.1.2 "StatusBar"
cordova-plugin-whitelist 1.2.1 "Whitelist"
ionic-plugin-keyboard 2.0.1 "Keyboard"
```

**Comment by orilux** [comment]
Hi @Valkno, I've posted a solution to this on AdMobPro's issues page: https://github.com/floatinghotpot/cordova-admob-pro/issues/286#issuecomment-171845551

You may also be able to save yourself the trouble of going through these steps by hard-coding version 8.+ on the following line of plugin.xml: https://github.com/ConnectSDK/Connect-SDK-Cordova-Plugin/blob/master/plugin.xml#L77

however i have not tried that myself and I am not sure it will actually work.

**Comment by Valkno** [comment]
Hi, Thank!, Follow the steps and worked perfectly!.
You should try to pull request with these changes.

**Comment by orilux** [comment]
Glad it worked. This SDK has been abandoned by LG so there is no point in doing a pull request. A fork was started at https://github.com/BeamSDK/Connect-SDK-Cordova-Plugin, where I might do the fix.
