### ISSUE TITLE
Cordova HLS

### ISSUE THREAD

**Issue by dankunwizard** [ConnectSDK/Connect-SDK-Cordova-Plugin#51]
I can successfully play Sintel movie over Chromecast following the cordova plugin documentation (http://www.svlconnectsdk.com/docs/1-6-0/cordova/discover-connect/) but HLS isn't working. I've tried different MIME values but no luck. Does the plugin support HLS?

**Comment by xjeeh** [comment]
did you found the solution? I'm facing the same issue..
