### ISSUE TITLE
ConnectSDK.discoveryManager.startDiscovery causes app to crash on Android 7.0

### ISSUE THREAD

**Issue by scottmizo** [ConnectSDK/Connect-SDK-Cordova-Plugin#55]
Cordova 5.4.1
Cordova Android 4.1.1
Connect-SDK-Cordova-Plugin 1.6
Android 7.0

When calling ConnectSDK.discoveryManager.startDiscovery(), the app crashes.
Error occurs with a custom app and connectsdk.cordova_api_sampler.
Error is not present with Android 6

Stack trace:

WhisperLink: WhisperLinkPlatform - bindSdk: app=com.connectsdk.cordova_api_sampler
WhisperLink: WhisperLinkPlatform - bindSdk: done, result=true
System.err: java.net.SocketException: Socket closed
System.err:   	at java.net.PlainDatagramSocketImpl.receive0(Native Method)
System.err:   	at java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:147)
System.err:   	at java.net.DatagramSocket.receive(DatagramSocket.java:811)
System.err:   	at com.connectsdk.discovery.provider.ssdp.SSDPClient.multicastReceive(SSDPClient.java:109)
System.err:   	at com.connectsdk.discovery.provider.SSDPDiscoveryProvider$4.run(SSDPDiscoveryProvider.java:268)
System.err:   	at java.lang.Thread.run(Thread.java:761)
System.err: java.net.SocketException: Socket closed
System.err:   	at java.net.PlainDatagramSocketImpl.receive0(Native Method)
System.err:   	at java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:147)
System.err:   	at java.net.DatagramSocket.receive(DatagramSocket.java:811)
System.err:   	at com.connectsdk.discovery.provider.ssdp.SSDPClient.multicastReceive(SSDPClient.java:109)
System.err:   	at com.connectsdk.discovery.provider.SSDPDiscoveryProvider$4.run(SSDPDiscoveryProvider.java:268)
System.err:   	at java.lang.Thread.run(Thread.java:761)

**Comment by scottmizo** [comment]
After a little debugging, here are some notes:

1) The issue only occurs when passing capability filters to startDiscovery.
2) Definitely related to SSDPDiscoveryProvider.
3) It looks like the provider is spawning multiple SSDPClients due to isRunning being false. Could be happening when the client is restarted after applying filters?

Simple work around is not to send capability filters.

**Comment by scottmizo** [comment]
Some more notes:

It looks like something is up with the responseThread and notifyThread not being properly interrupted.  If I call stop instead of interrupt, everything works again.  Less than ideal since stop is deprecated and highly discouraged.

**Comment by scottmizo** [comment]
Final solution:

Calling stop on the thread actually didn't do anything since Cordova threw and error.  Turns out that datagramSocket.disconnect() was hanging the thread.   Is disconnect necessary?

**Comment by alexb-geronimo** [comment]
@scottmizo Can u please tell me how did u solve this? U just updated the 'com.connectsdk:connect-sdk-android:1.6.0' or you did something extra in your code, like not disconnecting something?

**Comment by scottmizo** [comment]
@alexb-geronimo Yes.  Remove the datagramSocket.disconnect() from the SSDPClient.

https://github.com/ConnectSDK/Connect-SDK-Android-Core/pull/93/commits/edc686aaa0eed1cdac5e70b97c050ebb69c04d5f
