### ISSUE TITLE
shouldLoop not working

### ISSUE THREAD

**Issue by manifestinteractive** [ConnectSDK/Connect-SDK-Cordova-Plugin#7]
Greetings,

I am not having any luck getting `shouldLoop` to work on any device ( tried Apple TV, Chromecast & Roku ) using either Android or iOS via this Cordova Plugin.

This is the code I am using to test ( uses a 10 second video ):

```js
var devicePicker = ConnectSDK.discoveryManager.pickDevice();
devicePicker.success(function (device) {
	device.on("ready", function () {
		device.getMediaPlayer().playMedia(
			'http://bd-preview.s3.amazonaws.com/472537.mp4', 
			'video/mp4', 
			{
				title: 'Sample Short Video',
				description: 'A Blackdove Digital Art Piece',
				shouldLoop: true
			}
		).success(function (launchSession, mediaControl) {
			console.log("Video launch successful");
			window.controller = mediaControl && mediaControl.acquire();
		}).error(function (err) {
			console.log("error: " + err.message);
		});
	});
	device.connect();
});
```

The video plays fine but stops after playing once.

I have tried the following options without success:

```js
shouldLoop: 1
shouldLoop: true
```

I also noticed a possible bug in the `ConnectSDKCordovaDispatcher.m` file that looks to be preventing `shouldLoop` from ever being set.

The current code looks like this ( with my log statement added ):

```objc
if (options[@"shouldLoop"] == [NSNumber numberWithBool:YES]) {
    shouldLoop = YES;
    NSLog(@"Looping Enabled");
}
```

but that conditional never happens, however, updating the code to:

```objc
if ([options[@"shouldLoop"] isEqualToNumber:[NSNumber numberWithBool:YES]]) {
    shouldLoop = YES;
    NSLog(@"Looping Enabled");
}
```

does at least set shouldLoop to YES... however, it still never actually loops the video.

Am I missing something?

**Comment by Andolamin** [comment]
Looping is dependent on platform support and is only supported on webOS, currently.
